apiVersion: v1
kind: Service
metadata:
  name: artemis-broker-service
  namespace: activemq-artemis-operator
  labels: 
    operated-prometheus: "true"
spec:
  selector:
    ActiveMQArtemis: ex-aao
    application: ex-aao-app
  ports:
  - name: metrics
    protocol: TCP
    port: 8161
    targetPort: 8161
  type: ClusterIP