apiVersion: v1
kind: Service
metadata:
  labels:
    ActiveMQArtemis: ex-aao
    application: ex-aao-app
  name: artemis-broker-nodeport-service
  namespace: activemq-artemis-operator
spec:
  ports:
  - name: metrics
    protocol: TCP
    port: 8161
    targetPort: 8161
    nodePort: 30008  
  selector:
    ActiveMQArtemis: ex-aao
    application: ex-aao-app
  type: NodePort
